FROM docker.pkg.github.com/danmichaelo/skosmos-stack/skosmos-base:latest
ARG COMPOSER_AUTH

RUN apt-get update && \
  apt-get -y install zip unzip libzip-dev zlib1g-dev git \
  && docker-php-ext-install zip

COPY . /var/www/html

RUN curl -sS https://getcomposer.org/installer | php --
RUN php composer.phar install --no-interaction --no-dev --no-suggest --optimize-autoloader --profile
